package com.senchas.salvo;

public abstract class RandomStartingNames
{
    public final static String STARTING_NAMES[] = {
        "Andrew",
        "Art",
        "Arthur",
        "Athena",
        "Ballmer",
        "Barfy",
        "Bart",
        "Batman",
        "Belmont",
        "Ben-hur",
        "Braddock",
        "Caesar",
        "Carter",
        "Charlemagne",
        "Cheney",
        "Clinton",
        "Col. Sanders",
        "Cornelius",
        "Dante",
        "Dio",
        "Donnie",
        "Fat Tony",
        "Franz",
        "Frylock",
        "Gullifty",
        "G.W.",
        "Hermes",
        "Homer",
        "Isaac",
        "Jeff K.",
        "Jeff",
        "Jerry",
        "John",
        "Johnson",
        "Julius",
        "K.G.",
        "Kafka",
        "Katrina",
        "Kerrigan",
        "Leibowski",
        "Locutus",
        "Mammon",
        "Manbat",
        "Mario",
        "Mars",
        "Master Shake",
        "Matthew",
        "Meatwad",
        "Moe",
        "Montreal",
        "Moriarty",
        "Mr. Burns",
        "Napoleon",
        "Notorious AIG",
        "Putin",
        "Randal",
        "Richter",
        "Robotnik",
        "Roboturkey",
        "Shiva",
        "Shmorky",
        "Silent Bob",
        "Sirius",
        "Sisyphus",
        "Smithers",
        "Smoochy",
        "Spiff",
        "Stewie",
        "Terminator",
        "Ultros",
        "Una Persona",
        "Vladimir",
        "Vishnu",
        "Wolfe",
        "Wumpus",
        "Zardoz",
        "Zephyr",
        "Zeus",
    };
}
